# Generated by Django 5.2 on 2025-05-22 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_productvariant_price_product_price'),
        ('wishlist', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to='products.size'),
        ),
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('user', 'variant', 'size')},
        ),
    ]
