# Generated by Django 5.2 on 2025-05-24 04:05

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Unique code for the coupon (e.g., SAVE10).', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of the coupon.', null=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', help_text='Type of discount: percentage or fixed amount.', max_length=20)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Discount percentage (e.g., 10 for 10%). Required if discount type is percentage.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.01, message='Discount percentage must be greater than 0.'), django.core.validators.MaxValueValidator(100.0, message='Discount percentage cannot exceed 100%.')])),
                ('discount_value', models.DecimalField(blank=True, decimal_places=2, help_text='Discount value for fixed amount (e.g., $10). Required if discount type is fixed.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.01, message='Discount value must be greater than 0.')])),
                ('minimum_purchase_amount', models.DecimalField(decimal_places=2, help_text='Minimum purchase amount required to apply the coupon.', max_digits=10, validators=[django.core.validators.MinValueValidator(0.0, message='Minimum purchase amount cannot be negative.')])),
                ('max_discount_amount', models.DecimalField(decimal_places=2, default=200.0, help_text='Maximum discount amount for percentage-based coupons.', max_digits=10, validators=[django.core.validators.MinValueValidator(0.0, message='Maximum discount amount cannot be negative.')])),
                ('valid_from', models.DateTimeField(help_text='Date and time when the coupon becomes valid.')),
                ('valid_until', models.DateTimeField(help_text='Date and time when the coupon expires.')),
                ('usage_limit', models.PositiveIntegerField(default=1, help_text='Number of times this coupon can be used.', validators=[django.core.validators.MinValueValidator(1, message='Usage limit must be at least 1.')])),
                ('times_used', models.PositiveIntegerField(default=0, help_text='Number of times this coupon has been used.')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('expired', 'Expired')], default='active', help_text='Current status of the coupon.', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the coupon is active and can be used.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='coupon.coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Coupon Usage',
                'verbose_name_plural': 'Coupon Usages',
                'unique_together': {('user', 'coupon')},
            },
        ),
    ]
