# Generated by Django 5.2 on 2025-05-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0002_remove_coupon_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='times_used',
        ),
        migrations.AddField(
            model_name='couponusage',
            name='times_used',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this coupon has been used.'),
        ),
    ]
