# Generated by Django 5.2 on 2025-05-19 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_alter_order_shipping_address'),
        ('checkout', '0002_order_manual_status_update_alter_order_id_and_more'),
    ]

    operations = [
    ]
