# Generated by Django 5.2 on 2025-05-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_merge_20250519_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('order_placed', 'Order Placed'), ('shipped', 'Shipped'), ('out_for_delivery', 'Out For Delivery'), ('delivered', 'Delivered'), ('canceled', 'Canceled'), ('return_requested', 'Return Requested'), ('return', 'Return'), ('return_denied', 'Return Denied')], default='order_placed', max_length=20),
        ),
    ]
