# Generated by Django 5.2 on 2025-06-02 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_order_razorpay_order_id_order_razorpay_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product_variant',
        ),
    ]
