# Generated by Django 5.2 on 2025-05-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Discount amount applied by the coupon.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='discounted_total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total after applying coupon discount and shipping.', max_digits=10, null=True),
        ),
    ]
