# Generated by Django 5.2 on 2025-04-29 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='variant_image',
            field=models.ImageField(blank=True, null=True, upload_to='variant_images/'),
        ),
    ]
