# Generated by Django 5.2 on 2025-04-29 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productvariant_variant_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='variant_image',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='image_main',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
